language: python

python:
  - 2.6
  - 2.7
  - 3.3

install:
  # workaround for travis build vm's and multiprocessing
  # see https://github.com/travis-ci/travis-core/issues/187
  - sudo rmdir /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  # install dependencies
  - pip install -r requirements.txt --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install nose --use-mirrors
  # install bucky2
  - pip install -e . --use-mirrors

script:
  - flake8 --ignore=E501,W391 .
  - nosetests -v
