language: ruby
rvm:
  - 1.8.7
  - 1.9.2
script:
  - "rake lint"
  - "rake spec"
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.0
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.17
gemfile: .gemfile
notifications:
  email:
    - richard@ispavailability.com
